pipeline {
    agent {
        dockerfile {
            dir '02/solution'
        }
    }
    stages {
        stage('Verify') {
            steps {
                sh '''
                    node --version
                    npm version
                '''
            }
        }

        stage('Build') {
            steps {
                sh 'docker build -t jtrillo/jenkins-pipeline:0.0.1 .'
            }
        }

        stage('Smoke Test') {
            steps {
                sh 'docker run jtrillo/jenkins-pipeline:0.0.1'
            }
        }
    }
}