library identifier: 'jenkins-library-sessions@master'
        retriever: modernSCM([$class: 'GitSCMSource', remote: 'https://github.com/JTrillo/jenkins-library-sessions.git'])

pipeline {
    agent any
    stages {
        stage('Audit tools') {
            auditTools()
        }
    }
}