pipeline {
    agent any
    environment {
        RELEASE='0.0.1'
    }

    stages {
        stage('Build') {
            agent any
            environment {
                LOG_LEVEL='INFO'
            }
            parallel {
                stage('linux') {
                    steps {
                        echo "Building release ${RELEASE} for ${STAGE_NAME}"
                    }
                }
                stage('windows') {
                    steps {
                        echo "Building release ${RELEASE} for ${STAGE_NAME}"
                    }
                }
            }
        }
        stage('Test') {
            steps {
                echo "Testing release ${RELEASE}..."
            }
        }
        stage('Deploy') {
            input {
                message 'Deploy?'
                ok 'Do it!'
                parameters {
                    string(name: 'TARGET_ENVIRONMENT', defaultValue: 'PROD', description: "Target deployment environment")
                }
            }
            steps {
                echo "Deploying release ${RELEASE} to environment ${TARGET_ENVIRONMENT}"
            }
        }
    }

    post {
        always {
            echo "Prints success or failure"
        }
    }
}